# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps: 
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pipelines-conn'
    subscriptionId: '08335517-f87b-4ad8-ab7b-64a80313767b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'armtemplatepipelines'
    location: 'UK South'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Zororaa/Pipeline-repo-ForDelete/0077bc51b6ad2afd9270021b9af628b3e68a0bb1/CreateWebApp/azuredeploy.json?token=AOZJ6NOWK4NFSWM45VWFJ63B3WQWW'
    overrideParameters: '-projectName armpipe'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'